### ISSUE TITLE
프로젝트모집 회원가입, 로그인, 마이페이지 퍼블리싱

### ISSUE THREAD

**Issue by king-dong-gun** [PKNU-JavaStudy/mo.zip_frontend#25]
## 어떤 기능인가요?
회원가입, 로그인, 마이페이지 프론트 작업

> 추가하려는 기능에 대해 간결하게 설명해주세요

## 작업 상세 내용

- [ ] #29 회원가입 페이지 html, css 파일 생성 -> 확인 필요
- [ ] TODO
- [ ] TODO

**Comment by LegSmith** [comment]
한 페이지당 이슈1개씩 해서 하셈
